name: srtparse CI/CD action
on: [push]
jobs:
  test-code:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mkdir ~/virtualenv
      - name: Creating python virtualenv
        run: python3 -m venv ~/virtualenv/srtparse_virtualenv
      - run: cd $GITHUB_WORKSPACE
      - name: Installing dependencies
        run: pip3 install -r ./requirements.txt
      - name: Running unit tests
        run: python -m unittest discover test/