name: srtparse CI/CD action
on: [push]
jobs:
  test-code:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting job 'build documentation'"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mkdir ~/virtualenv
      - name: Creating python virtualenv
        run: python3 -m venv ~/virtualenv/srtparse_virtualenv
      - run: cd $GITHUB_WORKSPACE
      - name: Installing dependencies
        run: pip3 install -r ./requirements.txt
      - run: cd docs
      - name: Building docs
        run: make html
      - run: echo "Job 'build documentation' finished"
  build-documentation:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - run: cd $GITHUB_WORKSPACE
      - run: pwd
      - run: ls -l